###
GET http://localhost:4004/odata/v4/Studentservice/Students



###
POST http://localhost:4004/odata/v4/Studentservice/Students
Content-Type: application/json

{
  "name":"Nigil",
   "ID" : "STUD0006",
   "roll_no":2,
   "class":"X",
   "valueCreated":""
  
}